---
- name: Add elasticsearch repository
  template:
    backup: no
    dest: /etc/yum.repos.d/elasticsearch.repo
    group: "{{ es_system_group }}"
    owner: "{{ es_system_user }}"
    mode: 0644
    src: "{{ role_path }}/templates/yum/elasticsearch.repo.j2"

- name: Install elasticsearch package(s)
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - "elasticsearch-{{ es_version_full }}"
