---
- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Add kibana configuration file - kibana.yml
  template:
    backup: no
    dest: /etc/kibana/kibana.yml
    group: "{{ kb_system_group }}"
    owner: "{{ kb_system_user }}"
    mode: 0644
    src: "{{ role_path }}/templates/kibana/kibana.yml.j2"
  notify: Restart kibana.service

- name: Create kibana's data and log directory
  file:
    path: "{{ item }}"
    state: directory
    group: "{{ kb_kibana_group }}"
    owner: "{{ kb_kibana_user }}"
    mode: 0755
    recurse: no
  with_items: "{{ kb_dirs }}"

- name: Ensure kibana.service is enabled and started
  systemd:
    name: kibana
    daemon-reload: yes
    enabled: yes
    masked: no
    state: started
    no_block: no

- meta: flush_handlers
