---
- name: Add kibana repository
  template:
    backup: no
    dest: /etc/yum.repos.d/kibana.repo
    group: "{{ kb_system_group }}"
    owner: "{{ kb_system_user }}"
    mode: 0644
    src: "{{ role_path }}/templates/yum/kibana.repo.j2"

- name: Install kibana package(s)
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - "kibana-{{ kb_version_full }}"
