---

- name: fluentd daemonset installation
  hosts: kubernetes_master
  gather_facts: no
  remote_user: vagrant
  become: yes
  any_errors_fatal: true
  tags:
    - fluentd
    - efk
  roles:
    - fluentd
