---
# Common
es_version_major: 7.x
es_version_full: 7.2.0
es_network_interface: eth1
es_system_group: root
es_system_user: root
es_elastic_group: elasticsearch
es_elastic_user: elasticsearch
es_var_sysctls:
  - key: vm.max_map_count
    value: 262144
es_cluster_name: elasticsearch
es_data_path: /opt/elasticsearch/data
es_log_path: /opt/elasticsearch/logs
es_dirs:
  - "{{ es_data_path }}"
  - "{{ es_log_path }}"
es_bootstrap_memory_lock_enabled: "false"
es_http_port: 9200
es_transport_port: 9300
es_discovery_type: not-single-node

# Debian
es_apt_key_url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
es_apt_repository_url: "deb https://artifacts.elastic.co/packages/{{ es_version_major }}/apt stable main"
